spring:
  application:
    name: book-store
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db
    username: root
    password: Mysqlroot*-789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

